Adding a new problem
tsani/coding-cat-public pull request #6
Opened 2024-11-01 13:15 UTC by AlerGames

For assignment 3 of SF-1 ~~~ :3

2024-11-01 23:33 UTC, samchouse requested changes
LGTM other than this :D

2024-11-01 23:33 UTC, samchouse commented on sum-oddneven-index/description.md
> +- `sum(22,11,33) → 22 + 33 = 55`
```suggestion
- `sum_oddneven_list([1,2,3,4,5,6,7,8,9,10]) → 2 + 4 + 6 + 8 + 10 = 30`
- `sum_oddneven_list([111, 1]) → 1`
- `sum_oddneven_list([22,11,33]) → 22 + 33 = 55`
```

2024-11-03 23:21 UTC, AlerGames commented on sum-oddneven-index/description.md
> +- `sum(22,11,33) → 22 + 33 = 55`
very durr, thanks

2024-11-04 05:16 UTC, samchouse approved these changes

2024-11-04 19:21 UTC, emaj9 commented on sum-oddneven-index/io.json
> +		"input": [1,2,3,4,5,6,7],
this needs double [[ ]]

2024-11-06 18:12 UTC, merged